### ISSUE TITLE
作为一个小白部署到本地遇到的一些小建议

### ISSUE THREAD

**Issue by lizimu1013** [Qquanwei/gante#9]
作为一个小白部署到本地遇到的一些小问题：
1、Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './src/prop' is not defined by "exports" in D:\gante-master\gante-master\node_modules\ramda\package.json

解决方法：    package.json中修改"ramda": "^0.29.0"，升级到0.29.0版本

2、能否新增支持多选，然后同时拖动的功能。或者互相关联的任务拖动时，能同时一起拖动的功能

**Comment by Qquanwei** [comment]
hh 不错的建议，框选和分组是我一直想加的功能，对任务管理挺重要的。这条issue会加入到我的todo里。

**Comment by Qquanwei** [comment]
```
1、Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './src/prop' is not defined by "exports" in D:\gante-master\gante-master\node_modules\ramda\package.json
```

我本地使用的是 0.28.0 版本，没有这个报错，你的执行步骤是什么，或者有没有相关链接

**Comment by lizimu1013** [comment]
npm install后，直接npm run dev，就报错了

**Comment by Qquanwei** [comment]
node版本太高，v14,v16 可以正常使用。
